export const deepDives: Record<string, { title: string; paragraphs: string[] }[]> = {
  'arbiter-ai': [
    {title: 'Why a hybrid triage engine?', paragraphs: ['A queue of alerts is not yet a queue of decisions. An analyst still needs to connect the event to the affected asset, previous observations and the rules that apply. Arbiter explores how to make that first pass repeatable while keeping its reasoning available for review.', 'Deterministic rules handle cases where the system already has enough information. Local inference is reserved for ambiguity. This avoids asking a model to reconsider every clear rule match and gives the model a narrower job: interpret context inside boundaries enforced by code.']},
    {title: 'What the system actually produces', paragraphs: ['The central output is a recorded verdict with its rationale and supporting evidence. SQLite supplies historical context and stores decisions; the audit record preserves how an event was handled. Dashboard views expose that record through a JSON API.', 'The demonstration uses sample events. Shadow mode and response dry-run defaults let the decision path be inspected before any operational response is considered. A suggested verdict is therefore distinct from an action taken on a host.']},
    {title: 'How context enters without becoming permission', paragraphs: ['The engine checks dangerous patterns before inference, then lets the pre-filter resolve clear cases. An ambiguous event receives scoped history, asset criticality and administrator-curated facts before reaching Ollama.', 'A matching curated fact can send a specific guardrail hit for model review, but does not grant suppression by itself. After inference, the suppression threshold and applicable guardrail veto still matter. Model failure or insufficient confidence routes the event to review instead of silently discarding it.']},
    {title: 'A concrete route through the design', paragraphs: ['Consider an event whose meaning depends on whether the activity was expected on that host. With no decisive rule match, the engine gathers context and asks the local model for a verdict. A request to suppress with confidence below 0.7 becomes an escalation; an accepted verdict is recorded with its rationale.', 'This example explains the implemented control path, not a measured detection result. The repository’s evaluation artifacts help inspect particular failure modes, including an attack described as maintenance; broader collector integration and operational validation remain separate work.']},
  ],
  'trustkit-ai': [
    {title: 'Why a tour needs context', paragraphs: ['A remote renter sees a selective view of a property. A listing makes claims, while a tour provides incomplete visual evidence. TrustKit explores bringing those inputs together so a person can ask better follow-up questions before trusting what they see.', 'The useful output is an observation or inconsistency to investigate. Blur, darkness or an unusual frame can have ordinary explanations, so the product should preserve uncertainty rather than turn a visual heuristic into an accusation.']},
    {title: 'What I built within the team system', paragraphs: ['My work focused on frame extraction, metadata analysis and vision processing. Representative frames carry timestamps, and sampling limits and resizing bound the amount of media processed. The quality module measures blur using Laplacian variance and brightness using pixel intensity.', 'These measurements describe frame quality; they are not authentication of the video. Gemini vision adds observations, while the broader interface, voice experience, listing comparison and reasoning orchestration belong to the team project.']},
    {title: 'How live and uploaded tours differ', paragraphs: ['Live Copilot receives a JPEG frame over a WebSocket and runs quality and vision analysis concurrently. It combines those observations with listing claims, sends an alert response and continues the session. Per-frame failure has a fallback path so the connection can continue.', 'The uploaded-video path saves a temporary file, samples frames, then runs quality and vision in sequence for each frame. The current combined assessment uses the first frame’s observations even though the report contains multi-frame arrays. With an address, a separate comparison can use the first three tour frames and listing information. Temporary-file cleanup runs when processing ends.']},
    {title: 'Why those boundaries matter', paragraphs: ['Sampling keeps processing manageable but can miss a brief detail between frames. Using only the first frame for the combined assessment also limits how much of a tour that assessment represents. These are implementation constraints a reviewer should understand before interpreting the report.', 'Some vision paths return mock observations when configuration or inference fails. A successful interface response alone therefore does not demonstrate real model analysis or validated fraud detection. The next evaluation question is whether observations are useful and accurately tied to the media a renter actually supplied.']},
  ],
  'ssh-honeypot': [
    {title: 'Why observe a session rather than a connection count?', paragraphs: ['An SSH connection log tells you that someone connected. It does not explain the sequence of commands they attempted or the output they saw. This lab explores collecting that richer interaction as a session that can be reconstructed later.', 'The system separates an observer, responsible for the SSH connection and evidence, from a disposable execution environment. The aim is to study behavior while keeping the manager’s own shell out of the normal command path.']},
    {title: 'What lives on each side of the boundary', paragraphs: ['The Python manager owns Paramiko transport, authentication events, shell channels and session records. Docker supplies a container for a session, and commands are executed through docker exec. Metadata, event records and a transcript preserve different views of the interaction.', 'A container is a useful lifecycle and resource boundary, not proof of safe isolation. Resource limits and no-new-privileges constrain execution, while network isolation still depends on explicit configuration. The intended environment is an authorized, controlled lab.']},
    {title: 'How the command loop works', paragraphs: ['A connection creates a session record and establishes the SSH transport. Once a shell channel is available, the manager prepares the session container. It reads a command, handles working-directory changes, executes the command inside the container and returns output to the SSH client.', 'The loop repeats until the session ends. Recording both command events and visible output helps distinguish what was requested from what the environment returned. Container cleanup ends the execution environment while the evidence remains available locally for inspection.']},
    {title: 'What an investigation can learn', paragraphs: ['A useful review follows the session timeline: authentication attempts, commands, changes of directory and returned output. For example, a command that tries to read a file is more meaningful when its response is visible alongside it. A transcript supports that reconstruction without assuming every attempted command succeeded.', 'The next hardening questions concern enforced network restrictions, access to the manager and its Docker privileges, and reliable cleanup under failure. The project demonstrates the session and evidence pipeline; it does not claim that exposing a container-backed honeypot publicly is automatically safe.']},
  ],
};
