import { projects } from './projects';
export type WorkCategory = 'Security' | 'Applied AI' | 'Web & design' | 'Early work' | 'Research';
export type Work = { id: string; name: string; category: WorkCategory; status: string; summary: string; detail: string; stack: string; repository: string | null; caseStudy: string | null; symbol: string };
const repo = (name: string) => `https://github.com/Haryshwa29/${name}`;
export const work: Work[] = [
  ...projects.slice(0, 3).map((p, index): Work => ({ id: p.slug, name: p.name, category: index === 1 ? 'Applied AI' : 'Security', status: p.status, summary: p.title, detail: p.contribution, stack: p.technologies.join(' · '), repository: p.repository, caseStudy: `/projects/${p.slug}`, symbol: ['A', 'T', 'S'][index] })),
  { id: 'ssh-honeypot', name: 'SSH Honeypot', category: 'Security', status: 'Lab implementation', summary: 'Observing SSH sessions through a Docker-backed deception environment.', detail: 'Python and Paramiko handle SSH sessions, start per-session containers, and record authentication, command, and transcript data. The code adds resource limits and no-new-privileges. Network isolation depends on explicit configuration; the manager does not enforce an internal network by default. Intended for an authorized, controlled lab—not a claim of safe public deployment.', stack: 'Python · Paramiko · Docker', repository: repo('ssh-honeypot'), caseStudy: '/projects/ssh-honeypot', symbol: 'H' },
  { id: 'financial-rag', name: 'Financial RAG Analyst', category: 'Applied AI', status: 'Team project', summary: 'Exploring company filings through retrieval-assisted questions and answers.', detail: 'A collaborative project combining SEC 10-K document processing, semantic and keyword retrieval, and a Streamlit interface. The repository includes specialist analysis agents and citation-oriented answers. My repository is a team fork; individual module ownership is not claimed. Outputs require source checking and are not investment advice. Runtime and financial accuracy were not independently validated.', stack: 'Python · OpenAI · ChromaDB · BM25', repository: repo('rag_analyst'), caseStudy: '/projects/financial-rag', symbol: 'R' },
  { id: 'medai', name: 'MedAI', category: 'Applied AI', status: 'Team hackathon prototype', summary: 'Rubric-based feedback for medical students’ presentation practice.', detail: 'Built with a Rutgers Health Hack team to explore feedback on History & Physical presentations from audio or text. My repository description identifies my contribution as the rubrics and logic used by the AI. The source includes an evaluator, transcription integration, and a React interface. Educational prototype; no clinical validation or autonomous grading reliability is claimed.', stack: 'Python · React · AI evaluation', repository: repo('RU-HealthHack'), caseStudy: '/projects/medai', symbol: 'M' },
];
