import Link from 'next/link';
import { ArrowUpRight, ArrowDown, Plus, Download, Linkedin, Github, Mail } from 'lucide-react';
import { ClosingQuote } from '@/components/closing-quote';
import { Portrait } from '@/components/portrait';
import { ProjectGallery } from '@/components/project-gallery';
import { Contact } from '@/components/site-shell';
import { TriageDemo } from '@/components/triage-demo';
import { profile } from '@/content/profile';
import { experience } from '@/content/experience';
import { site, pageMetadata } from '@/lib/site-config';
export const metadata = { ...pageMetadata(site.title, site.description, '/'), title: { absolute: site.title } };
export default function Home() {
  const person = { '@context': 'https://schema.org', '@type': 'Person', name: profile.name, alternateName: profile.fullName, ...(site.origin ? { url: site.origin } : {}), sameAs: [profile.linkedin, profile.github], alumniOf: [{ '@type': 'CollegeOrUniversity', name: 'Stevens Institute of Technology' }, { '@type': 'CollegeOrUniversity', name: 'VIT Bhopal' }] };
  return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(person).replace(/</g, '\\u003c') }} />
    <section className="introduction wrap" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="tiny-rule" />Cybersecurity · Security automation</p><h1 id="hero-title">Hi, I’m<br /><span className="full-name-prefix">Thaithe Kalathil </span><em>Haryshwa Nair.</em></h1><p className="intro-location">Based in the NYC area · Open to relocation</p><p className="intro-lead">I build practical tools to understand threats<br className="desktop-break" /> and make security work clearer.</p><p className="hero-description">Cybersecurity graduate. Hands-on builder. I explore threat detection, security automation, and thoughtful uses of AI—with SOC experience at Deloitte and an M.S. from Stevens.</p><div className="hero-actions"><a className="button button-navy" href="#work">View Projects <ArrowDown size={17} aria-hidden="true" /></a>{profile.resume && <a className="button button-resume" href={profile.resume.url} download={profile.resume.filename}>Download Resume <Download size={17} aria-hidden="true" /></a>}<div className="hero-socials"><a href={profile.linkedin} aria-label="LinkedIn" title="LinkedIn"><Linkedin size={20} aria-hidden="true" /></a><a href={profile.github} aria-label="GitHub" title="GitHub"><Github size={20} aria-hidden="true" /></a>{profile.email && <a href={`mailto:${profile.email}`} aria-label="Email Haryshwa" title="Email Haryshwa"><Mail size={20} aria-hidden="true" /></a>}</div></div><p className="opportunity"><span />Open to early-career security engineering & automation roles.</p></div><Portrait /><div className="intro-foot"><span>Security, built with intent.</span><span>SCROLL TO EXPLORE <ArrowDown size={12} aria-hidden="true" /></span></div></section>
    <div className="foundation"><div className="wrap"><span className="eyebrow">Grounded in practice</span><span>Stevens Institute of Technology</span><span>Deloitte <small> / SOC Internship</small></span><span>Certified Ethical Hacker</span></div></div>
    <section id="work" className="collection wrap" aria-labelledby="work-title" data-reveal><div className="collection-heading"><div><p className="eyebrow">01 / Selected builds & explorations</p><h2 id="work-title">Projects <em>& research.</em></h2></div><p>Security tools, collaborative experiments,<br />and the work that started it all.</p></div><ProjectGallery /><div className="collection-foot"><p>Built, explored, or still on the drawing board.<br />Each project tells you where it stands.</p><Link className="text-link" href="/work">Open the full collection <ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>
    <section className="spotlight" aria-labelledby="spotlight-title" data-reveal><div className="wrap spotlight-grid"><div><p className="eyebrow">In focus · Security engineering</p><h2 id="spotlight-title">Arbiter AI</h2><p className="spotlight-subtitle">Local AI for alert triage.<br /><em>Guardrails before judgment.</em></p><p>What happens when a model mistakes an attack for routine maintenance? That question led me to put deterministic guardrails around local AI.</p><Link className="text-link" href="/projects/arbiter-ai">Inside the engineering decision <ArrowUpRight size={17} aria-hidden="true" /></Link></div><TriageDemo /></div></section>
    <section id="experience" className="journey wrap" aria-labelledby="experience-title" data-reveal><div className="collection-heading"><div><p className="eyebrow">02 / Professional & community journey</p><h2 id="experience-title">Experience<br /><em>& leadership.</em></h2></div><p>From the SOC to a developer community.<br />Showing up, learning, and contributing.</p></div><div className="journey-list">{experience.map((item, index) => <details key={item.role} className="journey-item"><summary><span className="journey-number">0{index + 1}</span><span className="journey-main"><span className="journey-kind">{item.kind}</span><strong>{item.organization}</strong><span>{item.role}</span></span><span className="journey-period">{item.period}</span><Plus size={20} aria-hidden="true" /></summary><div className="journey-expanded"><p>{item.description}</p><p>{item.details}</p></div></details>)}</div></section>
    <section id="about" className="credentials" aria-labelledby="about-title"><div className="wrap">
      <div className="collection-heading" data-reveal><div><p className="eyebrow">03 / The foundation behind the work</p><h2 id="about-title">Education <em>& achievements.</em></h2></div><p>Computer science foundations.<br />A deeper focus on cybersecurity.</p></div>
      <div className="education-grid" data-reveal>
        <article className="education-card"><p className="credential-label">Graduate education <span>2024–2026</span></p><h3>M.S. Cybersecurity</h3><p className="institution">Stevens Institute of Technology</p><p className="credential-context">My graduate education anchors my focus on threat detection, security automation, and practical security engineering.</p></article>
        <article className="education-card"><p className="credential-label">Undergraduate education <span>2020–2024</span></p><h3>B.Tech Computer Science<br />and Engineering</h3><p className="institution">VIT Bhopal</p><p className="credential-context">The computer science foundation behind my work across software, applied AI, and security.</p></article>
      </div>
      <div className="achievement-grid" data-reveal>
        <section className="credential-group" aria-labelledby="certifications-title"><h3 id="certifications-title">Certifications & training</h3><div className="credential-row"><span>01</span><div><h4>Certified Ethical Hacker</h4><p>Professional certification</p></div></div><div className="credential-row"><span>02</span><div><h4>TryHackMe Cybersecurity 101</h4><p>Course completion</p></div></div><div className="credential-row"><span>03</span><div><h4>Digital Forensics & Electronic Evidence</h4><p>Training</p></div></div></section>
        <section className="credential-group personal-achievements" aria-labelledby="achievements-title"><h3 id="achievements-title">Beyond technology</h3><p className="achievement-statement">Shotokan Karate<br /><em>Black belt.</em></p><div className="achievement-medal"><span>National bronze medalist</span><p>Discipline and commitment extend beyond the work I build.</p></div><p className="achievement-community">Badminton is another part of that journey—from volunteering to an elected club officer role at Stevens.</p></section>
      </div>
      <div className="practice-strip"><h3>What I bring to the work</h3><ul><li>Python & security automation</li><li>Alert triage & Splunk Enterprise Security</li><li>API integration & practical AI</li><li>Evidence-led testing & documentation</li></ul></div>
    </div></section>
    <ClosingQuote /><Contact />
  </main>;
}
