import Link from 'next/link';
import { ArrowUpRight, ArrowDown, ArrowRight } from 'lucide-react';
import { Architecture } from '@/components/architecture';
import { Contact } from '@/components/site-shell';
import { projects } from '@/content/projects';
import { profile } from '@/content/profile';
import { site, pageMetadata } from '@/lib/site-config';
export const metadata = { ...pageMetadata(site.title, site.description, '/'), title: { absolute: site.title } };
export default function Home() {
  const person = { '@context': 'https://schema.org', '@type': 'Person', name: profile.name, alternateName: profile.fullName, ...(site.origin ? { url: site.origin } : {}), sameAs: [profile.linkedin, profile.github], alumniOf: [{ '@type': 'CollegeOrUniversity', name: 'Stevens Institute of Technology' }, { '@type': 'CollegeOrUniversity', name: 'VIT Bhopal' }] };
  return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(person).replace(/</g, '\\u003c') }} />
    <section className="hero wrap" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="tiny-rule" />Haryshwa Nair / Cybersecurity</p><h1 id="hero-title">Security, built<br />with <em>intent.</em></h1><p className="hero-description">I build practical tools for threat detection, security automation, and AI-assisted defense. M.S. Cybersecurity from Stevens, with SOC internship experience at Deloitte.</p><div className="hero-actions"><a className="button button-gold" href="#work">Explore selected work <ArrowDown size={17} aria-hidden="true" /></a>{profile.resume && <a className="text-link" href={profile.resume.url}>View resume <ArrowUpRight size={16} aria-hidden="true" /></a>}</div><p className="opportunity"><span />Focused on early-career opportunities in<br className="desktop-break" /> security engineering and automation.</p></div><div className="hero-visual"><div className="visual-kicker"><span>Inside the work</span><span>01 / Arbiter AI</span></div><Architecture /><Link href="/projects/arbiter-ai" className="visual-caption">A closer look at local-first security <ArrowUpRight size={17} aria-hidden="true" /></Link></div></section>
    <div className="credibility wrap"><span className="credibility-label">A foundation in<br />theory & practice</span><span>Stevens Institute of Technology</span><span>Deloitte <span className="muted">· SOC Internship</span></span><span>CEH</span></div>
    <section className="work wrap section-space" id="work" aria-labelledby="work-title"><div className="section-top"><div><p className="eyebrow">Selected work / 01—03</p><h2 id="work-title">Built to ask better questions.<br /><em>And find useful answers.</em></h2></div><p className="section-aside">Three explorations in making<br />security more practical.</p></div>
      {projects.map((project, i) => <article className={`project-row ${i === 1 ? 'reverse' : ''}`} key={project.slug}><div className="project-copy"><div className="project-meta"><span className="chapter">{project.number}</span><span>{project.category}</span></div><h3><Link href={`/projects/${project.slug}`}>{project.name}</Link></h3><p className="project-position">{project.title}</p><p className="project-summary">{project.summary}</p><p className="project-status"><span />{project.status}</p><p className="tech-line">{project.technologies.join(' / ')}</p><Link className="text-link" href={`/projects/${project.slug}`}>Explore the case study <ArrowUpRight size={18} aria-hidden="true" /></Link></div><div className="project-art"><Architecture variant={project.slug} compact /></div></article>)}
    </section>
    <section className="ivory-section" aria-label="Background"><div className="wrap"><section className="experience section-space" id="experience" aria-labelledby="experience-title"><div className="section-top"><div><p className="eyebrow">Experience & community</p><h2 id="experience-title">Learning in the field.<br /><em>Contributing beyond it.</em></h2></div></div><div className="experience-grid"><div className="experience-intro"><p>Security is a technical discipline.<br />It is also a team effort.</p><p>My experience spans SOC workflows, hands-on building, and bringing people together.</p></div><div className="experience-list"><article><div className="experience-heading"><h3>Deloitte India</h3><span>Oct 2023 — Jan 2024</span></div><h4>SOC Intern</h4><p>Worked with Splunk Enterprise Security in banking and insurance environments. Supported alert triage and escalation to L2/L3 analysts.</p></article><article><div className="experience-heading"><h3>GDG Brooklyn</h3><span>Jul — Sep 2026</span></div><h4>Social Media & Volunteer Lead</h4><p>Contributed to the local developer community through social media and volunteer leadership.</p></article><article><div className="experience-heading"><h3>Stevens Graduate Badminton Club</h3></div><h4>Graduate Badminton Club Officer · Jan 2025–May 2026</h4><p>Coordinated events, court time, equipment, and student outreach to create a welcoming place to play.</p></article></div></div></section>
    <section className="about section-space" id="about" aria-labelledby="about-title"><div className="about-intro"><p className="eyebrow">A little about me</p><h2 id="about-title">Curiosity, with<br /><em>follow-through.</em></h2><p>I’m Haryshwa—a cybersecurity graduate who likes turning a security question into something I can build, test, and improve.</p><p>I’m drawn to preventing cyber fraud, automating the repetitive parts of defense, and finding privacy-conscious uses for AI. I’m just as interested in where a system fails as where it works.</p><p className="personal-note">Away from the keyboard: a Shotokan Karate black belt, national bronze medalist, and badminton enthusiast.</p></div><div className="about-details"><div><h3>Education</h3><h4>M.S. Cybersecurity</h4><p>Stevens Institute of Technology · 2026</p><h4>B.Tech Computer Science and Engineering</h4><p>VIT Bhopal · 2020–2024</p></div><div><h3>Certification & training</h3><h4>Certified Ethical Hacker</h4><p>Professional certification</p><h4>TryHackMe Cybersecurity 101</h4><p>Course completion</p><h4>Digital Forensics & Electronic Evidence</h4><p>Training</p></div><div><h3>What I bring</h3><p className="capabilities">Python & security automation<br />Alert triage & Splunk Enterprise Security<br />API integration & practical AI<br />Evidence-led testing & documentation</p></div></div></section></div></section>
    <section className="approach wrap"><span className="eyebrow">The thread through my work</span><p>Build thoughtfully.<br />Test the assumptions.<br /><em>Make the reasoning visible.</em></p><ArrowRight size={38} strokeWidth={1} aria-hidden="true" /></section><Contact />
  </main>;
}

